// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASVB1aTjcrGElyQbuan_GDes1-9nU0a9k',
    appId: '1:455725713809:android:68adf236e724d087757230',
    messagingSenderId: '455725713809',
    projectId: 'joyway-58ef5',
    storageBucket: 'joyway-58ef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV1epbbKUHlPKLm6XCSUEXzGt0XvlwlCo',
    appId: '1:455725713809:ios:c690fa828101ade8757230',
    messagingSenderId: '455725713809',
    projectId: 'joyway-58ef5',
    storageBucket: 'joyway-58ef5.firebasestorage.app',
    iosBundleId: 'com.example.joyWay',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9W91NkMwk5RCvpgXnxkmzxxgWQI1mgxE',
    appId: '1:455725713809:web:cf734d35abedabd4757230',
    messagingSenderId: '455725713809',
    projectId: 'joyway-58ef5',
    authDomain: 'joyway-58ef5.firebaseapp.com',
    storageBucket: 'joyway-58ef5.firebasestorage.app',
    measurementId: 'G-SFF215ESQD',
  );

}